// Generated by `go run ./cmd/wiregen` from the server's Go types (game/view.go, game/clock.go, game/rematch.go, game/live.go, server/me.go)
// and the rules engine's numbers. Don't edit it: change the Go and run the
// command again. `go test ./cmd/wiregen` fails while it is out of date.

export type Color = 'white' | 'black';

/** Where a game is in its life. */
export type Status = 'waiting' | 'playing' | 'over';

/**
 * View is one subscriber's picture of the game, sent as the SSE "state"
 * event after every change. It is the whole game, so a reconnecting browser
 * needs nothing else. Views are shared between streams: read them, never
 * change them.
 */
export interface View {
	code: string;
	status: Status;
	/** "white", "black" or "spectator" */
	you: Color | 'spectator';
	/** index 0 = a1; "" or color+kind: "wP", "bQ" */
	board: string[];
	/** its square, "" once it has fallen */
	mamdani: string;
	potholes: Pothole[];
	/** "white" or "black" */
	turn: Color;
	check: boolean;
	/** only for the player to move */
	legal: MoveJSON[];
	/** what happened on the latest turn, in order */
	last: EventJSON[];
	/** one entry per turn */
	log: LogEntry[];
	/** pieces each side has lost to potholes */
	lost: LostJSON;
	stats: StatsJSON;
	result: ResultJSON | null;
	/** turns played; a move must quote it */
	seq: number;
	clock: ClockJSON;
	/** which players have the game open */
	online: OnlineJSON;
	/** names; "" for a seat that is empty or was saved without one */
	players: PlayersJSON;
	/** only once the game is over */
	rematch: RematchJSON;
}

/**
 * Pothole is an open pothole, the color that rolled it and its rounds left:
 * how many more of By's moves it stays open for (1 to rules.HoleRounds).
 */
export interface Pothole {
	sq: string;
	by: Color;
	left: number;
}

/** MoveJSON is a move on the wire. Promo is "", "q", "r", "b" or "n". */
export interface MoveJSON {
	from: string;
	to: string;
	promo?: string;
}

/** EventJSON is one step of a turn. Only the fields that apply to Kind are set. */
export interface EventJSON {
	kind: string;
	sq?: string;
	from?: string;
	to?: string;
	promo?: string;
	piece?: string;
	color?: Color;
	roll?: number;
	saved?: boolean;
	reason?: string;
}

/**
 * LogEntry is one turn in the move log: the move in algebraic notation and
 * what the dice did, e.g. {"e4", "white", "d8 4 → c3"}.
 */
export interface LogEntry {
	san: string;
	color: Color;
	dice: string;
}

/** LostJSON lists the pieces each side has lost to potholes, as piece codes. */
export interface LostJSON {
	white: string[];
	black: string[];
}

/** StatsJSON counts what the dice and the Mamdani have done this game. */
export interface StatsJSON {
	savingRolls: number;
	saved: number;
	/** potholes the Mamdani fixed */
	repaired: number;
	mamdaniFell: boolean;
}

/**
 * ResultJSON is how the game ended. Winner is "" for a draw, and for an
 * aborted or expired game, which nobody wins.
 */
export interface ResultJSON {
	/** "" for a draw */
	winner?: Color;
	draw: boolean;
	reason: string;
}

/**
 * ClockJSON is the clocks on the wire. The browser counts down locally:
 * the running side has its remaining time minus (its now − since), where
 * its now is shifted by the difference between Now and its own clock.
 */
export interface ClockJSON {
	whiteMs: number;
	blackMs: number;
	/** "white", "black" or "" when stopped */
	running?: Color;
	/**
	 * Since is when the running clock starts or started, in unix ms. It can
	 * be after Now during the dice pause.
	 */
	since?: number;
	/** Now is the server's time when the view was built, in unix ms. */
	now: number;
	/**
	 * FirstMoveDeadline is when the side to move must make its first move
	 * by, in unix ms; 0 outside the first moves.
	 */
	firstMoveDeadline?: number;
}

/** OnlineJSON says which players have a stream open. */
export interface OnlineJSON {
	white: boolean;
	black: boolean;
}

/** PlayersJSON is each seat's name, as it was when its player sat down. */
export interface PlayersJSON {
	white: string;
	black: string;
}

/** RematchJSON is the rematch on the wire. */
export interface RematchJSON {
	/** the color that offered, while waiting */
	offer?: Color;
	declined?: boolean;
	/** set once accepted: everyone goes there */
	code?: string;
}

/**
 * Live is a game as the home page's live games list shows it. A game
 * replaces its Live after every call; a published Live is never changed.
 */
export interface Live {
	code: string;
	/** names */
	white: string;
	black: string;
	/** the full-move number being played */
	move: number;
	board: string[];
	mamdani: string;
	potholes: Pothole[];
	/** the latest move, or null before the first */
	last: MoveJSON | null;
	/** guests watching who aren't playing */
	watching: number;
}

/**
 * MeJSON is the caller's name and name changes on the wire. ChangesResetAt
 * is when they get store.NameChanges again (Unix ms), or null while none
 * are used.
 */
export interface MeJSON {
	name: string | null;
	changesLeft: number;
	changesResetAt: number | null;
	/**
	 * Game is the code of the game the caller is playing right now, or
	 * null, so a page can offer to take them back to it.
	 */
	game?: string;
}

/** How many of its roller's moves a pothole stays open for (rules.HoleRounds). */
export const HOLE_ROUNDS = 3;
/** The most potholes open at once; opening one more closes the oldest (rules.HoleCap). */
export const HOLE_CAP = 5;
