// Command wiregen writes web/src/lib/wire.gen.ts: the TypeScript types of
// the server's JSON (the game view, the live games list, the guest's name)
// and the numbers the browser shares with the rules engine, generated from
// the Go types so the browser's copy can't drift. Run it from the repo root
// after changing a wire type:
//
//	go run ./cmd/wiregen
//
// The types come from reflection; their comments come from the Go source.
// A field whose TypeScript type is narrower than its Go type (a color is a
// Go string) says so with a ts struct tag, e.g. `ts:"Color"`.
package main

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"log"
	"os"
	"path/filepath"
	"reflect"
	"strings"

	"mamdani-chess/game"
	"mamdani-chess/rules"
	"mamdani-chess/server"
)

// outFile is where the generated file goes, from the repo root.
const outFile = "web/src/lib/wire.gen.ts"

// types are the structs written out, in order.
var types = []any{
	game.View{}, game.Pothole{}, game.MoveJSON{}, game.EventJSON{}, game.LogEntry{},
	game.LostJSON{}, game.StatsJSON{}, game.ResultJSON{}, game.ClockJSON{},
	game.OnlineJSON{}, game.PlayersJSON{}, game.RematchJSON{}, game.Live{}, server.MeJSON{},
}

// sources hold the types' comments.
var sources = []string{"game/view.go", "game/clock.go", "game/rematch.go", "game/live.go", "server/me.go"}

func main() {
	if _, err := os.Stat("go.mod"); err != nil {
		log.Fatal("run wiregen from the repo root")
	}
	out, err := generate(".")
	if err != nil {
		log.Fatal(err)
	}
	if err := os.WriteFile(outFile, []byte(out), 0o644); err != nil {
		log.Fatal(err)
	}
}

// generate returns the file's contents. root is the repo root.
func generate(root string) (string, error) {
	docs, err := comments(root)
	if err != nil {
		return "", err
	}
	var b strings.Builder
	b.WriteString("// Generated by `go run ./cmd/wiregen` from the server's Go types (" + strings.Join(sources, ", ") + ")\n")
	b.WriteString("// and the rules engine's numbers. Don't edit it: change the Go and run the\n")
	b.WriteString("// command again. `go test ./cmd/wiregen` fails while it is out of date.\n\n")
	fmt.Fprintf(&b, "export type Color = '%s' | '%s';\n\n", rules.White, rules.Black)
	fmt.Fprintf(&b, "/** Where a game is in its life. */\nexport type Status = '%s' | '%s' | '%s';\n", game.Waiting, game.Playing, game.Over)
	for _, v := range types {
		t := reflect.TypeOf(v)
		if docs[t.Name()] == "" {
			return "", fmt.Errorf("no doc comment for %s: add its file to sources", t.Name())
		}
		b.WriteString("\n")
		writeComment(&b, "", docs[t.Name()])
		fmt.Fprintf(&b, "export interface %s {\n", t.Name())
		for f := range t.Fields() {
			name, optional, ok := jsonName(f)
			if !ok {
				continue
			}
			tsType, nullable := tsTypeOf(f.Type)
			if tag := f.Tag.Get("ts"); tag != "" {
				tsType = tag
			}
			if nullable && !optional {
				tsType += " | null"
			}
			writeComment(&b, "\t", docs[t.Name()+"."+f.Name])
			mark := ""
			if optional {
				mark = "?"
			}
			fmt.Fprintf(&b, "\t%s%s: %s;\n", name, mark, tsType)
		}
		b.WriteString("}\n")
	}
	b.WriteString("\n/** How many of its roller's moves a pothole stays open for (rules.HoleRounds). */\n")
	fmt.Fprintf(&b, "export const HOLE_ROUNDS = %d;\n", rules.HoleRounds)
	b.WriteString("/** The most potholes open at once; opening one more closes the oldest (rules.HoleCap). */\n")
	fmt.Fprintf(&b, "export const HOLE_CAP = %d;\n", rules.HoleCap)
	return b.String(), nil
}

// jsonName returns f's JSON key and whether it is left out when empty, or
// false for a field that isn't sent.
func jsonName(f reflect.StructField) (name string, omitempty, ok bool) {
	if !f.IsExported() {
		return "", false, false
	}
	tag := f.Tag.Get("json")
	if tag == "-" {
		return "", false, false
	}
	name, opts, _ := strings.Cut(tag, ",")
	if name == "" {
		name = f.Name
	}
	return name, strings.Contains(opts, "omitempty"), true
}

// tsTypeOf returns the TypeScript type for t, and whether the value can be
// null (a pointer).
func tsTypeOf(t reflect.Type) (string, bool) {
	if t == reflect.TypeFor[game.Status]() {
		return "Status", false
	}
	switch t.Kind() {
	case reflect.Pointer:
		inner, _ := tsTypeOf(t.Elem())
		return inner, true
	case reflect.Slice, reflect.Array:
		inner, _ := tsTypeOf(t.Elem())
		return inner + "[]", false
	case reflect.Struct:
		return t.Name(), false
	case reflect.String:
		return "string", false
	case reflect.Bool:
		return "boolean", false
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64,
		reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64, reflect.Float32, reflect.Float64:
		return "number", false
	}
	panic("wiregen: no TypeScript type for " + t.String())
}

// comments reads the doc and line comments of the types and their fields,
// keyed "Type" and "Type.Field".
func comments(root string) (map[string]string, error) {
	out := map[string]string{}
	fset := token.NewFileSet()
	for _, src := range sources {
		f, err := parser.ParseFile(fset, filepath.Join(root, src), nil, parser.ParseComments)
		if err != nil {
			return nil, err
		}
		for _, decl := range f.Decls {
			gd, ok := decl.(*ast.GenDecl)
			if !ok || gd.Tok != token.TYPE {
				continue
			}
			for _, spec := range gd.Specs {
				ts := spec.(*ast.TypeSpec)
				st, ok := ts.Type.(*ast.StructType)
				if !ok {
					continue
				}
				doc := ts.Doc
				if doc == nil && len(gd.Specs) == 1 {
					doc = gd.Doc
				}
				out[ts.Name.Name] = doc.Text()
				for _, field := range st.Fields.List {
					text := field.Doc.Text()
					if text == "" {
						text = field.Comment.Text()
					}
					for _, n := range field.Names {
						out[ts.Name.Name+"."+n.Name] = text
					}
				}
			}
		}
	}
	return out, nil
}

// writeComment writes text as a JSDoc comment, one line if it fits.
func writeComment(b *strings.Builder, indent, text string) {
	text = strings.TrimSpace(text)
	if text == "" {
		return
	}
	lines := strings.Split(text, "\n")
	if len(lines) == 1 {
		fmt.Fprintf(b, "%s/** %s */\n", indent, lines[0])
		return
	}
	fmt.Fprintf(b, "%s/**\n", indent)
	for _, l := range lines {
		fmt.Fprintf(b, "%s * %s\n", indent, strings.TrimRight(l, " "))
	}
	fmt.Fprintf(b, "%s */\n", indent)
}
